fixed udata var, added error bailouts

diff --git a/bin/mt-backup b/bin/mt-backup
--- a/bin/mt-backup
+++ b/bin/mt-backup
@@ -20,9 +20,10 @@ exit
 fi
 
 if [[ "$1" = backup ]]; then
-	aname="$(date "+%F-%T").tar.gz"
-	tar czf "$aname" -C / "$MT_DATA" "$MT_GDATA" "$MT_LDATA" "$MT_CONF"
-	echo "[1;33mData saved at $aname[0m"
+	aname="$(date "+%F-%T"|sed -r 's/[^[0-9-]+//g').tar.gz"
+	(tar czf "$aname" -C / "$MT_UDATA" "$MT_GDATA" "$MT_LDATA" "$MT_CONF" &&
+		echo "[1;32mData saved at $aname[0m") ||
+		{ echo "[1;31mBackup failed[0m" ; exit 1 ; }
 elif [[ "$1" = restore ]]; then
 	shift
 	if [[ -z "$*" ]]; then
@@ -35,7 +36,7 @@ elif [[ "$1" = restore ]]; then
 		exit 1
 	fi
 
-	"$0" backup # backup existing config just in case!
+	"$0" backup || { echo "[01;33mABORT[0m" ; exit 1; }  # backup existing config just in case!
 	set -e
 	(cd "$MT_GDATA" ; rm -r ./* )
 	(cd "$MT_UDATA" ; rm -r ./* )
