Added non-interactive mode

diff --git a/bin/mtctl b/bin/mtctl
--- a/bin/mtctl
+++ b/bin/mtctl
@@ -3,8 +3,9 @@
 function checkforplayers {
 	playerlist="$(grep -P -o "List of players:.+" /var/log/minetest/minetest.log|sed "s/List of players: //"|tail -n 1)"
 
-	if [[ -n "$playerlist" ]]; then
+	if [[ -n "$playerlist" ]] || [[ "$*" =~ '-y' ]]; then
 		echo "Players: $playerlist"
+		if [[ "$*" =~ "-n" ]]; then exit 1; fi
 		read -p "It seems there are still players online - are you sure? [y/N]> "
 		if [[ ! "$REPLY" =~ $(echo '^(yes|YES|y|Y)$') ]]; then
 			exit 1
@@ -14,24 +15,23 @@ function checkforplayers {
 }
 
 if [[ -z "$*" ]]; then
-	echo "No action specified. Actions: stop, start, restart"
+	echo "No action specified. Actions: stop, start, restart. Specify -y to force restart without prompt, specify -n to abort restart without prompt"
 	exit 1
 fi
 
-for action in "$1"; do
+action="$1" ; shift
 echo "Action: $1"
 case "$action" in
 	stop)
-		checkforplayers && systemctl stop minetest-server
+		checkforplayers "$@" && systemctl stop minetest-server
 		;;
 	start)
 		systemctl start minetest-server
 		;;
-	*)
-		checkforplayers && systemctl restart minetest-server
+	restart)
+		checkforplayers "$@" && systemctl restart minetest-server
 		;;
 esac
-done
 
 sleep 3
 journalctl -xe -u minetest-server|tail -n 20
